import * as esbuild from 'esbuild';
import process from 'process';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const watch = (process.argv[2] === 'watch');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['extension.ts'],
	bundle: true,
	external: [
		'vscode',
		'fs',
		'path',
		'os',
		'crypto',
		'events',
		'child_process',
		'http',
		'https',
		'url',
		'util',
		'stream',
		'buffer',
		'tty',
		'net',
		'tls',
		'zlib',
		'querystring'
	],
	format: 'cjs',
	minify: prod,
	sourcemap: prod ? false : 'inline',
	sourcesContent: false,
	platform: 'node',
	outfile: 'dist/extension.js',
	logLevel: "info",
});

if (watch) {
	console.log('👀 Watch mode enabled. Building...');
	
	await context.watch();
	
	// Listen for rebuild events
	context.watch().then(() => {
		console.log('🔄 Watching for file changes...');
	});
	
	// Handle rebuild events
	context.onEnd = (result) => {
		if (result.errors.length === 0) {
			console.log('✅ Build completed successfully');
		} else {
			console.log('❌ Build failed with errors');
		}
	};
	
	// Keep the process alive
	console.log('🚀 Watch mode is running. Press Ctrl+C to stop.');
} else {
	await context.rebuild();
	await context.dispose();
	process.exit(0);
}
