import * as esbuild from 'esbuild';
import * as fs from 'fs';
import * as path from 'path';
import process from 'process';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const __filename = new URL(import.meta.url).pathname;
const __dirname = path.dirname(__filename);

const prod = (process.argv[2] === 'production');
const watch = process.argv[2] === '--watch';

console.log('DEBUG: process.argv =', process.argv);
console.log('DEBUG: watch =', watch);

const srcDir = __dirname;
const distDir = path.join(__dirname, '../dist');

// Clean dist directory
if (fs.existsSync(distDir)) {
	fs.rmSync(distDir, { recursive: true, force: true });
}

const buildOptions = {
	banner: {
		js: banner,
	},
	plugins: [
		{
			name: 'copyFiles',
			setup(build) {
				build.onEnd(() => {
					const filesToCopy = [
						{ src: path.join(srcDir, '../README.md'), dest: path.join(distDir, 'README.md') },
						{ src: path.join(srcDir, '../CHANGELOG.md'), dest: path.join(distDir, 'CHANGELOG.md') },
						{ src: path.join(srcDir, '../LICENSE'), dest: path.join(distDir, 'LICENSE') },
					];
					
					// Copy .env if exists
					const envSrc = path.join(srcDir, '../.env');
					if (fs.existsSync(envSrc)) {
						filesToCopy.push({ src: envSrc, dest: path.join(distDir, '.env') });
					}
					
					// Copy vscode-material-icons if exists
					const iconsSrc = path.join(srcDir, '../node_modules/vscode-material-icons/generated');
					if (fs.existsSync(iconsSrc)) {
						fs.cpSync(iconsSrc, path.join(distDir, 'assets/vscode-material-icons'), { recursive: true });
					}
					
					// Copy webview-ui/audio if exists
					const audioSrc = path.join(srcDir, '../webview-ui/audio');
					if (fs.existsSync(audioSrc)) {
						fs.cpSync(audioSrc, path.join(distDir, 'webview-ui/audio'), { recursive: true });
					}
 
					// Copy webview-ui/dist if exists
					const webviewDistSrc = path.join(srcDir, '../webview-ui/dist');
					if (fs.existsSync(webviewDistSrc)) {
						fs.cpSync(webviewDistSrc, path.join(distDir, 'webview-ui/dist'), { recursive: true });
						console.log(`📄 Copied ${webviewDistSrc} -> ${path.join(distDir, 'webview-ui/dist')}`);
					}
 
					// Copy src/assets if exists
					const assetsSrc = path.join(srcDir, 'assets');
					if (fs.existsSync(assetsSrc)) {
						fs.cpSync(assetsSrc, path.join(distDir, 'assets'), { recursive: true });
						console.log(`📄 Copied ${assetsSrc} -> ${path.join(distDir, 'assets')}`);
					}
 
					// Copy files
					for (const { src, dest } of filesToCopy) {
						if (fs.existsSync(src)) {
							fs.copyFileSync(src, dest);
							console.log(`📄 Copied ${src} -> ${dest}`);
						}
					}

					// Copy and modify package.json for dist directory
					const packageJsonSrc = path.join(srcDir, 'package.json');
					const packageJsonDest = path.join(distDir, 'package.json');
					if (fs.existsSync(packageJsonSrc)) {
						const packageJson = JSON.parse(fs.readFileSync(packageJsonSrc, 'utf-8'));
						// Fix the main path for dist directory
						packageJson.main = 'extension.js';
						fs.writeFileSync(packageJsonDest, JSON.stringify(packageJson, null, 2));
						console.log(`📄 Copied and modified ${packageJsonSrc} -> ${packageJsonDest}`);
					}
				});
			},
		},
		{
			name: 'esbuild-problem-matcher',
			setup(build) {
				build.onStart(() => console.log('[esbuild-problem-matcher#onStart]'));
				build.onEnd((result) => {
					result.errors.forEach(({ text, location }) => {
						console.error(`✘ [ERROR] ${text}`);
						if (location && location.file) {
							console.error(`    ${location.file}:${location.line}:${location.column}:`);
						}
					});
					console.log('[esbuild-problem-matcher#onEnd]');
				});
			},
		},
	],
	entryPoints: [path.join(srcDir, 'extension.ts')],
	bundle: true,
	external: [
		'vscode',
		'fs',
		'path',
		'os',
		'crypto',
		'events',
		'child_process',
		'http',
		'https',
		'url',
		'util',
		'stream',
		'buffer',
		'tty',
		'net',
		'ls',
		'zlib',
		'querystring'
	],
	format: 'cjs',
	minify: prod,
	sourcemap: prod ? false : 'inline',
	sourcesContent: false,
	platform: 'node',
	outfile: path.join(distDir, 'extension.js'),
	logLevel: "info",
};

if (watch) {
	console.log('👀 Watch mode enabled. Building...');
	
	const ctx = await esbuild.context(buildOptions);
	await ctx.watch();
	
	console.log('🚀 Watch mode is running. Press Ctrl+C to stop.');
} else {
	await esbuild.build(buildOptions);
	process.exit(0);
}
