import * as esbuild from 'esbuild';
import * as fs from 'fs';
import * as path from 'path';
import process from 'process';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const __filename = new URL(import.meta.url).pathname;
const __dirname = path.dirname(__filename);

const prod = (process.argv[2] === 'production');
const watch = (process.argv[2] === 'watch');

const srcDir = __dirname;
const distDir = path.join(srcDir, 'dist');

// Clean dist directory
if (fs.existsSync(distDir)) {
	fs.rmSync(distDir, { recursive: true, force: true });
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	plugins: [
		{
			name: 'copyFiles',
			setup(build) {
				build.onEnd(() => {
					const filesToCopy = [
						{ src: path.join(srcDir, '../README.md'), dest: path.join(distDir, 'README.md') },
						{ src: path.join(srcDir, '../CHANGELOG.md'), dest: path.join(distDir, 'CHANGELOG.md') },
						{ src: path.join(srcDir, '../LICENSE'), dest: path.join(distDir, 'LICENSE') },
					];
					
					// Copy .env if exists
					const envSrc = path.join(srcDir, '../.env');
					if (fs.existsSync(envSrc)) {
						filesToCopy.push({ src: envSrc, dest: path.join(distDir, '.env') });
					}
					
					// Copy vscode-material-icons if exists
					const iconsSrc = path.join(srcDir, '../node_modules/vscode-material-icons/generated');
					if (fs.existsSync(iconsSrc)) {
						fs.cpSync(iconsSrc, path.join(distDir, 'assets/vscode-material-icons'), { recursive: true });
					}
					
					// Copy webview-ui/audio if exists
					const audioSrc = path.join(srcDir, '../webview-ui/audio');
					if (fs.existsSync(audioSrc)) {
						fs.cpSync(audioSrc, path.join(distDir, 'webview-ui/audio'), { recursive: true });
					}
					
					// Copy files
					for (const { src, dest } of filesToCopy) {
						if (fs.existsSync(src)) {
							fs.copyFileSync(src, dest);
							console.log(`📄 Copied ${src} -> ${dest}`);
						}
					}
				});
			},
		},
		{
			name: 'esbuild-problem-matcher',
			setup(build) {
				build.onStart(() => console.log('[esbuild-problem-matcher#onStart]'));
				build.onEnd((result) => {
					result.errors.forEach(({ text, location }) => {
						console.error(`✘ [ERROR] ${text}`);
						if (location && location.file) {
							console.error(`    ${location.file}:${location.line}:${location.column}:`);
						}
					});
					console.log('[esbuild-problem-matcher#onEnd]');
				});
			},
		},
	],
	entryPoints: ['extension.ts'],
	bundle: true,
	external: [
		'vscode',
		'fs',
		'path',
		'os',
		'crypto',
		'events',
		'child_process',
		'http',
		'https',
		'url',
		'util',
		'stream',
		'buffer',
		'tty',
		'net',
		'tls',
		'zlib',
		'querystring'
	],
	format: 'cjs',
	minify: prod,
	sourcemap: prod ? false : 'inline',
	sourcesContent: false,
	platform: 'node',
	outfile: 'dist/extension.js',
	logLevel: "info",
});

if (watch) {
	console.log('👀 Watch mode enabled. Building...');
	
	await context.watch();
	
	// Listen for rebuild events
	context.watch().then(() => {
		console.log('🔄 Watching for file changes...');
	});
	
	// Handle rebuild events
	context.onEnd = (result) => {
		if (result.errors.length === 0) {
			console.log('✅ Build completed successfully');
		} else {
			console.log('❌ Build failed with errors');
		}
	};
	
	// Keep the process alive
	console.log('🚀 Watch mode is running. Press Ctrl+C to stop.');
} else {
	await context.rebuild();
	await context.dispose();
	process.exit(0);
}
